### 1. Data extraction.

### 1.1 NASDAQ - CSV - Tesla historical stock price

In [1]:
import pandas as pd
import numpy as np
import re
import requests
pd.set_option("display.max_columns", None)

In [2]:
df=pd.read_csv(r'C:\Users\alexd\Ironhack\Proyectos\Project3_DA_Ironhack\Data\archive\HistoricalData_1656067143500.csv', encoding='latin1')

df

Fecha Cerrar/último   Volumen     Abrir       Alto     Bajo
0     06/23/2022        $705.21  34734230  $713.715    $717.95  $685.91
1     06/22/2022        $708.26  33842420   $703.51     $740.5  $701.48
2     06/21/2022        $711.11  40930990   $673.81  $730.7321     $673
3     06/17/2022        $650.28  30880590    $640.3  $662.9082  $639.59
4     06/16/2022         $639.3  35796900   $668.21     $675.5  $626.08
...          ...            ...       ...       ...        ...      ...
2511  06/29/2012         $6.258   5628520     $6.56      $6.56     $6.2
2512  06/28/2012         $6.282   4570200     $6.38     $6.422   $6.124
2513  06/27/2012         $6.392   5235970     $6.38     $6.489   $6.314
2514  06/26/2012         $6.322  13069245     $6.41      $6.47   $6.278
2515  06/25/2012         $6.622   7475870    $6.788     $6.824    $6.55

[2516 rows x 6 columns]

In [3]:
df.shape

(2516, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516 entries, 0 to 2515
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Fecha           2516 non-null   object
 1   Cerrar/último  2516 non-null   object
 2   Volumen         2516 non-null   int64 
 3   Abrir           2516 non-null   object
 4   Alto            2516 non-null   object
 5   Bajo            2516 non-null   object
dtypes: int64(1), object(5)
memory usage: 118.1+ KB


In [5]:
df.columns=[c.lower().replace(' ', '_') for c in df.columns]
df.columns=[c.lower().replace('cerrar/ãºltimo', 'cierre') for c in df.columns]

In [6]:
df.columns

Index(['fecha', 'cierre', 'volumen', 'abrir', 'alto', 'bajo'], dtype='object')

In [7]:
nan_cols=df.isnull().sum()
nan_cols[nan_cols>0] 

Series([], dtype: int64)

In [8]:
df.fecha=pd.to_datetime(df.fecha)

In [9]:
df['cierre'].replace('$','',inplace=True)

In [10]:
df.cierre=[e.replace('$', '') for e in df.cierre]

In [11]:
df.abrir=[e.replace('$', '') for e in df.abrir]

In [12]:
df.alto=[e.replace('$', '') for e in df.alto]

In [13]:
df.bajo=[e.replace('$', '') for e in df.bajo]

In [14]:
df

fecha  cierre   volumen    abrir      alto    bajo
0    2022-06-23  705.21  34734230  713.715    717.95  685.91
1    2022-06-22  708.26  33842420   703.51     740.5  701.48
2    2022-06-21  711.11  40930990   673.81  730.7321     673
3    2022-06-17  650.28  30880590    640.3  662.9082  639.59
4    2022-06-16   639.3  35796900   668.21     675.5  626.08
...         ...     ...       ...      ...       ...     ...
2511 2012-06-29   6.258   5628520     6.56      6.56     6.2
2512 2012-06-28   6.282   4570200     6.38     6.422   6.124
2513 2012-06-27   6.392   5235970     6.38     6.489   6.314
2514 2012-06-26   6.322  13069245     6.41      6.47   6.278
2515 2012-06-25   6.622   7475870    6.788     6.824    6.55

[2516 rows x 6 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516 entries, 0 to 2515
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   fecha    2516 non-null   datetime64[ns]
 1   cierre   2516 non-null   object        
 2   volumen  2516 non-null   int64         
 3   abrir    2516 non-null   object        
 4   alto     2516 non-null   object        
 5   bajo     2516 non-null   object        
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 118.1+ KB


In [16]:
df['cierre'] = df['cierre'].astype('float')
df['abrir'] = df['abrir'].astype('float')
df['alto'] = df['alto'].astype('float')
df['bajo'] = df['bajo'].astype('float')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516 entries, 0 to 2515
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   fecha    2516 non-null   datetime64[ns]
 1   cierre   2516 non-null   float64       
 2   volumen  2516 non-null   int64         
 3   abrir    2516 non-null   float64       
 4   alto     2516 non-null   float64       
 5   bajo     2516 non-null   float64       
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 118.1 KB


In [18]:
df['movimiento_diario']=df['cierre']-df['abrir']

In [19]:
df['year'] = pd.DatetimeIndex(df['fecha']).year

In [20]:
df['month'] = pd.DatetimeIndex(df['fecha']).month

In [21]:
df.head()

fecha  cierre   volumen    abrir      alto    bajo  movimiento_diario  \
0 2022-06-23  705.21  34734230  713.715  717.9500  685.91             -8.505   
1 2022-06-22  708.26  33842420  703.510  740.5000  701.48              4.750   
2 2022-06-21  711.11  40930990  673.810  730.7321  673.00             37.300   
3 2022-06-17  650.28  30880590  640.300  662.9082  639.59              9.980   
4 2022-06-16  639.30  35796900  668.210  675.5000  626.08            -28.910   

   year  month  
0  2022      6  
1  2022      6  
2  2022      6  
3  2022      6  
4  2022      6

### 1.2 Kaggle - CSV - Elon Musk historical tweets

In [22]:
df2=pd.read_csv(r'C:\Users\alexd\Ironhack\Proyectos\Project3_DA_Ironhack\Data\archive\elonmusk.csv', encoding='latin1')

df2.head()

Tweet UserScreenName   UserName                 Timestamp  \
0      0      Elon Musk  @elonmusk  2010-06-04T18:31:57.000Z   
1      1      Elon Musk  @elonmusk  2011-12-01T09:55:11.000Z   
2      2      Elon Musk  @elonmusk  2011-12-01T10:29:04.000Z   
3      3      Elon Musk  @elonmusk  2011-12-03T08:20:28.000Z   
4      4      Elon Musk  @elonmusk  2011-12-03T08:22:07.000Z   

                                                text Emojis Comments Likes  \
0  Please ignore prior tweets, as that was someon...    NaN      873   648   
1  Went to Iceland on Sat to ride bumper cars on ...    NaN       30    24   
2  I made the volume on the Model S http://ow.ly/...    NaN       29    17   
3  Great Voltaire quote, arguably better than Twa...    NaN       23    30   
4      That was a total non sequitur btw\n26\n14\n50    NaN       26    14   

  Retweets                                         Image link  \
0    5,453                                                 []   
1      188  ['https://pbs.twimg.com/media/Afkf5DMCAAEJGFr?...   
2       78                                                 []   
3       44                                                 []   
4       50                                                 []   

                                           Tweet URL  
0    https://twitter.com/elonmusk/status/15434727182  
1  https://twitter.com/elonmusk/status/1421799282...  
2  https://twitter.com/elonmusk/status/1421884581...  
3  https://twitter.com/elonmusk/status/1428808713...  
4  https://twitter.com/elonmusk/status/1428812840...

In [23]:
df2.shape

(12206, 11)

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12206 entries, 0 to 12205
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Tweet           12206 non-null  int64 
 1   UserScreenName  12206 non-null  object
 2   UserName        12206 non-null  object
 3   Timestamp       12206 non-null  object
 4   text            12206 non-null  object
 5   Emojis          854 non-null    object
 6   Comments        12186 non-null  object
 7   Likes           12183 non-null  object
 8   Retweets        12206 non-null  object
 9   Image link      12206 non-null  object
 10  Tweet URL       12206 non-null  object
dtypes: int64(1), object(10)
memory usage: 1.0+ MB


In [25]:
df2.columns=[c.lower().replace(' ', '_') for c in df2.columns]
df2.columns=[c.lower().replace('timestamp', 'post_time') for c in df2.columns]
df2.columns

Index(['tweet', 'userscreenname', 'username', 'post_time', 'text', 'emojis',
       'comments', 'likes', 'retweets', 'image_link', 'tweet_url'],
      dtype='object')

In [26]:
nan_cols=df2.isnull().sum()
nan_cols[nan_cols>0] 

emojis      11352
comments       20
likes          23
dtype: int64

In [27]:
del df2['tweet']
del df2['emojis']

In [28]:
df2["comments"].fillna("0", inplace = True)
df2["likes"].fillna("0", inplace = True)

In [29]:
def time(col):
    
    res1=[]
    
    
    for e in col:
        res1.append(e[0:10])
        
    return res1

In [30]:
df2['n_post_time']=time(df2.post_time)
df2.head()

userscreenname   username                 post_time  \
0      Elon Musk  @elonmusk  2010-06-04T18:31:57.000Z   
1      Elon Musk  @elonmusk  2011-12-01T09:55:11.000Z   
2      Elon Musk  @elonmusk  2011-12-01T10:29:04.000Z   
3      Elon Musk  @elonmusk  2011-12-03T08:20:28.000Z   
4      Elon Musk  @elonmusk  2011-12-03T08:22:07.000Z   

                                                text comments likes retweets  \
0  Please ignore prior tweets, as that was someon...      873   648    5,453   
1  Went to Iceland on Sat to ride bumper cars on ...       30    24      188   
2  I made the volume on the Model S http://ow.ly/...       29    17       78   
3  Great Voltaire quote, arguably better than Twa...       23    30       44   
4      That was a total non sequitur btw\n26\n14\n50       26    14       50   

                                          image_link  \
0                                                 []   
1  ['https://pbs.twimg.com/media/Afkf5DMCAAEJGFr?...   
2                                                 []   
3                                                 []   
4                                                 []   

                                           tweet_url n_post_time  
0    https://twitter.com/elonmusk/status/15434727182  2010-06-04  
1  https://twitter.com/elonmusk/status/1421799282...  2011-12-01  
2  https://twitter.com/elonmusk/status/1421884581...  2011-12-01  
3  https://twitter.com/elonmusk/status/1428808713...  2011-12-03  
4  https://twitter.com/elonmusk/status/1428812840...  2011-12-03

In [31]:
df2['n_post_time'] = pd.to_datetime(df2['n_post_time'])
del df2['post_time']

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12206 entries, 0 to 12205
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   userscreenname  12206 non-null  object        
 1   username        12206 non-null  object        
 2   text            12206 non-null  object        
 3   comments        12206 non-null  object        
 4   likes           12206 non-null  object        
 5   retweets        12206 non-null  object        
 6   image_link      12206 non-null  object        
 7   tweet_url       12206 non-null  object        
 8   n_post_time     12206 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(8)
memory usage: 858.4+ KB


In [33]:
df2.retweets=[c.lower().replace(',', '') for c in df2.retweets]
df2.comments=[c.lower().replace(',', '') for c in df2.comments]
df2.likes=[c.lower().replace(',', '') for c in df2.likes]

In [34]:
def exchange(col):
    
    res=[]
    
    number=1
    
    
    for e in col:
        if e[-1].isdigit():
            res.append(e)
            
        else:
        
            if e[-1]=='k':
                number=1e3
                n_col=re.findall('[0-9.]+', e)[0]
                res.append(int(float(n_col) * number))


            elif e[-1]=='K': 
                number=1e3
                n_col=re.findall('[0-9.]+', e)[0]
                res.append(int(float(n_col) * number))

            elif e[-1]=='M': 
                number=1e6
                n_col=re.findall('[0-9.]+', e)[0]
                res.append(int(float(n_col) * number))

            elif e[-1]=='m': 
                number=1e6
                n_col=re.findall('[0-9.]+', e)[0]
                res.append(int(float(n_col) * number))


            else:
                n_col=re.findall('[0-9.]+', e)[0]
                res.append(int(float(n_col) * number))
                   
    return res

In [35]:
exchange(['23333'])

['23333']

In [36]:
df2['n_retweets']=exchange(df2.retweets)


In [37]:
df2['n_comments']=exchange(df2.comments)


In [38]:
df2['n_likes']=exchange(df2.likes)

In [39]:
df2.head()

userscreenname   username  \
0      Elon Musk  @elonmusk   
1      Elon Musk  @elonmusk   
2      Elon Musk  @elonmusk   
3      Elon Musk  @elonmusk   
4      Elon Musk  @elonmusk   

                                                text comments likes retweets  \
0  Please ignore prior tweets, as that was someon...      873   648     5453   
1  Went to Iceland on Sat to ride bumper cars on ...       30    24      188   
2  I made the volume on the Model S http://ow.ly/...       29    17       78   
3  Great Voltaire quote, arguably better than Twa...       23    30       44   
4      That was a total non sequitur btw\n26\n14\n50       26    14       50   

                                          image_link  \
0                                                 []   
1  ['https://pbs.twimg.com/media/Afkf5DMCAAEJGFr?...   
2                                                 []   
3                                                 []   
4                                                 []   

                                           tweet_url n_post_time n_retweets  \
0    https://twitter.com/elonmusk/status/15434727182  2010-06-04       5453   
1  https://twitter.com/elonmusk/status/1421799282...  2011-12-01        188   
2  https://twitter.com/elonmusk/status/1421884581...  2011-12-01         78   
3  https://twitter.com/elonmusk/status/1428808713...  2011-12-03         44   
4  https://twitter.com/elonmusk/status/1428812840...  2011-12-03         50   

  n_comments n_likes  
0        873     648  
1         30      24  
2         29      17  
3         23      30  
4         26      14

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12206 entries, 0 to 12205
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   userscreenname  12206 non-null  object        
 1   username        12206 non-null  object        
 2   text            12206 non-null  object        
 3   comments        12206 non-null  object        
 4   likes           12206 non-null  object        
 5   retweets        12206 non-null  object        
 6   image_link      12206 non-null  object        
 7   tweet_url       12206 non-null  object        
 8   n_post_time     12206 non-null  datetime64[ns]
 9   n_retweets      12206 non-null  object        
 10  n_comments      12206 non-null  object        
 11  n_likes         12206 non-null  object        
dtypes: datetime64[ns](1), object(11)
memory usage: 1.1+ MB


In [41]:
del df2['likes']
del df2['comments']
del df2['retweets']

In [42]:
df2['n_likes'] = df2['n_likes'].astype('int')

In [43]:
df2['n_comments'] = df2['n_comments'].astype('int')

In [44]:
df2['n_retweets'] = df2['n_retweets'].astype('int')

In [45]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12206 entries, 0 to 12205
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   userscreenname  12206 non-null  object        
 1   username        12206 non-null  object        
 2   text            12206 non-null  object        
 3   image_link      12206 non-null  object        
 4   tweet_url       12206 non-null  object        
 5   n_post_time     12206 non-null  datetime64[ns]
 6   n_retweets      12206 non-null  int32         
 7   n_comments      12206 non-null  int32         
 8   n_likes         12206 non-null  int32         
dtypes: datetime64[ns](1), int32(3), object(5)
memory usage: 715.3+ KB


In [46]:
df2['year'] = pd.DatetimeIndex(df2['n_post_time']).year

In [47]:
df2['month'] = pd.DatetimeIndex(df2['n_post_time']).month

In [48]:
df2.columns=[c.lower().replace('n_post_time', 'date') for c in df2.columns]
df2.columns=[c.lower().replace('n_comments', 'comments') for c in df2.columns]
df2.columns=[c.lower().replace('n_likes', 'likes') for c in df2.columns]
df2.columns=[c.lower().replace('n_retweets', 'retweets') for c in df2.columns]

In [49]:
df2.head()

userscreenname   username  \
0      Elon Musk  @elonmusk   
1      Elon Musk  @elonmusk   
2      Elon Musk  @elonmusk   
3      Elon Musk  @elonmusk   
4      Elon Musk  @elonmusk   

                                                text  \
0  Please ignore prior tweets, as that was someon...   
1  Went to Iceland on Sat to ride bumper cars on ...   
2  I made the volume on the Model S http://ow.ly/...   
3  Great Voltaire quote, arguably better than Twa...   
4      That was a total non sequitur btw\n26\n14\n50   

                                          image_link  \
0                                                 []   
1  ['https://pbs.twimg.com/media/Afkf5DMCAAEJGFr?...   
2                                                 []   
3                                                 []   
4                                                 []   

                                           tweet_url       date  retweets  \
0    https://twitter.com/elonmusk/status/15434727182 2010-06-04      5453   
1  https://twitter.com/elonmusk/status/1421799282... 2011-12-01       188   
2  https://twitter.com/elonmusk/status/1421884581... 2011-12-01        78   
3  https://twitter.com/elonmusk/status/1428808713... 2011-12-03        44   
4  https://twitter.com/elonmusk/status/1428812840... 2011-12-03        50   

   comments  likes  year  month  
0       873    648  2010      6  
1        30     24  2011     12  
2        29     17  2011     12  
3        23     30  2011     12  
4        26     14  2011     12

### 1.3 BeautifulSoup Scraping - Timeline for Tesla

In [79]:
import requests as req

from bs4 import BeautifulSoup as bs

import pandas as pd

In [109]:
url='https://www.tradingview.com/symbols/NASDAQ-TSLA/history-timeline/#'

In [110]:
html=req.get(url).content

In [111]:
sopa=bs(html, 'html.parser')

In [112]:
todos_elementos=sopa.find('div', class_='js-feed-wrap')

In [113]:
data_1_elemento=todos_elementos.find_all('div', class_='container-jdFEaBiF')[0]

In [114]:
fecha=data_1_elemento.find('div', class_='date-jdFEaBiF').text.strip()

header=data_1_elemento.find('h4', class_='title-jdFEaBiF').text.strip()

cuerpo=data_1_elemento.find('span', class_='description-jdFEaBiF').text.strip()

In [115]:
{'fecha': fecha,
'header': header,
'cuerpo': cuerpo}

{'fecha': 'Jun 212022',
 'header': 'Is Elongate upon us?',
 'cuerpo': "Elon Musk is getting hit with lawsuits left right and center after a few months (years?) of keeping everyone on their toes.Tesla has been stung with another lawsuit. This one comes from two former employees, who claimed in a Sunday filing that the EV maker’s decision to lay off around 10% of Tesla staff required at least 60 days advance notice – which they apparently didn't get. Musk’s “super bad feeling about the economy” was at the root of the ~500-person layoff, according to his tweets anyway. Tesla has been hiring rapidly in the last few months despite economic uncertainty swirling, which is one of the reasons employees were surprised by layoffs. But, apparently the situation has become too tenuous, even for Elon.It was the second lawsuit of the week for Tesla and its famous/infamous CEO (depends who you ask). A Dogecoin investor, who intends to turn the suit into a class action, sued Elon Musk and his companies

In [116]:
def timeline(url):
    headers = {
    "User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
    }
    
    for i in range(1, 50):
        url = "https://www.tradingview.com/symbols/NASDAQ-TSLA/history-timeline/#" + str(i)
        r = req.get(url, headers=headers)
        sopa = bs(r.content, "html.parser")
    
        data=[] 

        for e in sopa.find('div', class_='js-feed-wrap').find_all('div', class_='container-jdFEaBiF'):

            fecha=e.find('div', class_='date-jdFEaBiF').text.strip()

            header=e.find('h4', class_='title-jdFEaBiF').text.strip()

            cuerpo=e.find('span', class_='description-jdFEaBiF').text.strip()

            data.append({'fecha': fecha,
                                 'header': header,
                                 'cuerpo': cuerpo})

        
    return pd.DataFrame(data)

In [117]:
timeline(url)

fecha                                  header  \
0   Jun 212022                    Is Elongate upon us?   
1   Jun 062022          The hiring tank is running low   
2   May 192022                        Tesla gets testy   
3   Apr 272022                       Delaware but here   
4   Apr 212022        Tesla races past its own records   
5   Apr 182022        Berlin Gigafactory holds its own   
6   Apr 182022  Tesla Insurance travels to more states   
7   Apr 182022    Mercedes challenges the charge crown   
8   Apr 162022                  A new Megapack is here   
9   Apr 152022                Musk gets mad at the SEC   
10  Apr 132022       Fake news fans Lithium Corp stock   
11  Apr 082022                     Two Blocks go solar   
12  Apr 072022                        Tesla the HODLer   
13  Apr 072022                             Rodeo drive   
14  Apr 062022               Shanghai is going bye bye   
15  Apr 042022          Tesla races across a milestone   
16  Mar 312022                       Solartime sadness   
17  Mar 292022                       Stock split bliss   
18  Mar 252022                     Yep, another recall   
19  Mar 222022                          Good day, mate   

                                               cuerpo  
0   Elon Musk is getting hit with lawsuits left ri...  
1   Macroeconomic headwinds continue to slow Tesla...  
2   Elon Musk goes on a heated Twitter rampage, la...  
3   Musk wins a shareholder battle over Tesla’s $2...  
4   Tesla lit up its stock with a 4/20 earnings re...  
5   A new report from Germany gives some insight i...  
6   Tesla Insurance, which is a growing division f...  
7   Tesla’s grip on the EV market’s wheel is looki...  
8   Tesla unveils its latest massive Megapack proj...  
9   Elon Musk claps back at the SEC regarding his ...  
10  A bunch of fans spread the distinctly fake new...  
11  Bitcoin firm Blockstream and Twitter founder J...  
12  An SEC filing reveals that Tesla now holds jus...  
13  Tesla holds its Cyber Rodeo party to commemora...  
14  A resurgence of Covid in China means Tesla’s S...  
15  Tesla is on the way to winning its game of cat...  
16  Tesla pauses installations of its solar roof t...  
17  Tesla tops off two weeks of stupendous gains w...  
18  Are Tesla customers sick of these recalls yet?...  
19  Tesla gets handed another massive battery cont...

In [106]:
for col in df:
  print(df[col].unique())

['2022-06-23T00:00:00.000000000' '2022-06-22T00:00:00.000000000'
 '2022-06-21T00:00:00.000000000' ... '2012-06-27T00:00:00.000000000'
 '2012-06-26T00:00:00.000000000' '2012-06-25T00:00:00.000000000']
[705.21  708.26  711.11  ...   6.392   6.322   6.622]
[34734230 33842420 40930990 ...  5235970 13069245  7475870]
[713.715 703.51  673.81  ...   6.27    6.38    6.41 ]
[717.95   740.5    730.7321 ...   6.489    6.47     6.824 ]
[685.91  701.48  673.    ...   6.2     6.314   6.278]
[-8.505e+00  4.750e+00  3.730e+01 ...  1.200e-02 -8.800e-02 -1.660e-01]
[2022 2021 2020 2019 2018 2017 2016 2015 2014 2013 2012]
[ 6  5  4  3  2  1 12 11 10  9  8  7]


In [108]:
df3=timeline(url)
len(df3)

20

In [ ]:
df3.to_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project3_DA_Ironhack\Data\timeline.xls', index=False)

### Conclusiones